ethereum-optimism/superchain-ops

mainnet-rehearsals/3-R4-upgrade-2-of-2/README.md
corrected a path + added clarification (feedback from the user to add reminder)
A clear and concise description of the features you're adding in this pull request.
**Tests**
Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
=> path + clarification on derivation

tasks/eth/2-add-superchainConfig/Validation.md
Adds a file describing the validations required for upgrade 4.
This PR is in draft, as instructions for using DiffyScan are still needed to validate the implementation code.
=> Add validations.md

tasks/eth/03-protocol-versions-delta/README.md
Adds the Final status to the Delta runbook, including links to the vote and non-veto.
=> Update delta runbook to final

tasks/eth/004-add-superchainConfig/README.md, tasks/eth/004-add-superchainConfig/Validation.md, tasks/eth/004-add-superchainConfig/justfile
Some fixes which address minor gaps in the eth/004 runbook executed yesterday.
=> Fixes to 004 Runbook

tasks/eth/002-pause-mainnet/README.md, tasks/eth/003-protocol-versions-delta/README.md, tasks/eth/004-add-superchainConfig/README.md
Updates runbooks which have been executed.
=> Update 002, 003 and 004 to EXECUTED with tx links

nested.just, single.just
Removes an unused argument from the single sign and execute commands and fixes bundlePath setting in the nested justfile
=> Fix Bundle Path Handling

tasks/eth/005-2-ecotone-set-gas-config/README.md
It got executed with https://etherscan.io/tx/0xac827d7a1238dfd6f3cc81dba09f0a3e1d9dc685bcc6b22466d76bb2335db38b
=> mainnet: update task 005-2 to executed status, add tx hash

tasks/eth/006-MCP-L1/VALIDATION.md
Fixes a small bug in the markdown file that prevents the markdown link
from rendering.
=> tasks: MCP fix markdown

NESTED.md, SINGLE.md, script/NestedSignFromJson.s.sol, script/SignFromInputJson.s.sol, script/SignFromJson.s.sol, single.just
This contains the non-metal aspects of https://github.com/ethereum-optimism/superchain-ops/pull/132:
- bump base-contracts and forge-std submodule versions
- improve copy in base READMEs
- leverage base-contracts improvements in our default scripts
- update single.just so its generic, not OP specific
=> chore: various improvements and cleanup

single.just
=> fix: rpc url

.circleci/config.yml, src/JsonTxBuilderBase.sol
There were already forge jobs defined in CI, but they weren't being run.
=> Add forge jobs to workflows

tasks/sep/mode-001-MCP-L1/README.md
=> task(mode-sep-MCP): set as READY TO SIGN

tasks/sep/metal-001-MCP-L1/README.md, tasks/sep/mode-001-MCP-L1/README.md
These tasks have been successfully executed by Conduit, cc @emilianobonassi
=> chore: update task statuses

tasks/eth/mode-001-MCP-L1/VALIDATION.md
There are multiple signers on the safe
=> doc: clarify nonce bump state change

src/JsonTxBuilderBase.sol
cc @emilianobonassi, give this PR a try
=> fix: skip precompile code check and silence compiler warnings

tasks/sep/zora-001-MCP-L1/README.md
Task executed with success. cc @mds1
=> chore(sep/zora): update task status to executed

PRESIGNED-PAUSE.md
Small change surfaced during signing with @mds1
=> Clarify parameter in psp instructions

tasks/sep/008-presigned-pause/README.md
Update status of 008-presigned-pause to signed
=> Update status of 008-presigned-pause to signed

.circleci/config.yml, tasks/sep/010-op-l2-predeploy-upgrade-from-l1/README.md
=> sep: EXECUTED: Upgrading L2 Predeploy From L1 Proxy Admin Owner #205

tasks/eth/009-fp-upgrade/VALIDATION.md
Documents the state overrides so signers can validate them
=> doc: add state overrides to FP task

tasks/eth/009-fp-upgrade/README.md, tasks/eth/010-1-guardian-upgrade/README.md, tasks/eth/010-2-sc-changes/README.md, tasks/eth/010-2-sc-changes/VALIDATION.md, tasks/oeth/002-update-l2pao-to-aliased-l1pao/README.md
Check status here before merging.
- https://snapshot.org/#/citizenshouse.eth/proposal/0xe2d86afceea73f2e2734550bec73af395b78826413fb3622b57dce43b2fd7b94
- https://snapshot.org/#/citizenshouse.eth/proposal/0x21f7126c1636cecdcf7522eadbf6e1b20ca22a2230faf871209fcd21dc999d81
=> Update Upgrade Playbook statuses

tasks/sep/base-001-MCP-L1/VALIDATION.md
Updating L1CrossDomainMessengerProxy to the correct Base Sepolia address
=> updating L1CrossDomainMessengerProxy

.circleci/config.yml, README.md
A little QoL improvement for debugging.
=> Add print_versions

tasks/eth/011-proto-ver+ownership-transfers/README.md, tasks/eth/012-proto-ver-required/README.md, tasks/eth/013-fp-upgrade-fjord/README.md, tasks/eth/014-fjord-gas-config/README.md
The veto period has been updated, so these status have all been changed accordingly
=> task status updates

.circleci/config.yml
=> ci: remove completed tasks

tasks/sep/base-002-fp-upgrade/README.md
Update status of task `base-002-fp-upgrade` from `DRAFT` to `READY TO SIGN`
=> Update Base Sepolia FP upgrade task status

script/utils/check-task-statuses.sh
The current error message suggests that a PR cannot be merged if it is labelled as in `DRAFT` status, this is true only because DRAFT doesn't match list of accepted statuses, not because the play book can't be in draft.
=> ci: Clarify what statuses are accepted

tasks/eth/mmz-002-key-handover/SignFromJson.s.sol
This is a PR building on top of #280, which fixes the `checkStateDiff()` implementation. 
My suggest on the Sepolia task was wrong and I'll open a PR to fix it as well.
=> Updates to mmz _postCheck()

script/DeployRehearsal4.s.sol, security-council-rehearsals/2024-02-03-r4-jointly-upgrade-0203/justfile, security-council-rehearsals/templates/r4-jointly-upgrade/justfile
Updates the name of the Rehearsal 4 deployment script, this helps to prepare for the Rehearsal 5 changes.
=> Update r4 deploy script name

tasks/sep/mmz-002-key-handover/SignFromJson.s.sol
Fixes an issue in #271 (introduced by my inline suggestion). The issues fixed are: 
1. `checkStateDiff` was not actually being run in the post check hook
2. `checkStateDiff` was reimplemented, whereas instead the functions it calls should have been implemented (i. `getAllowedStorageAccess` and `getCodeExceptions`)
=> Ensure checkStateDiff runs in _postcheck.

.env, tasks/sep/base-003-fp-granite-prestate/.env, tasks/sep/base-003-fp-granite-prestate/README.md, tasks/sep/base-003-fp-granite-prestate/SignFromJson.s.sol, tasks/sep/base-003-fp-granite-prestate/VALIDATION.md, tasks/sep/base-003-fp-granite-prestate/input.json
Copy of #293 but not on a fork
=> Base Sepolia Granite HF prestate upgrade

tasks/sep/base-004-fp-audit-fixes/README.md
Update status of task `tasks/sep/base-004-fp-audit-fixes` to executed.
=> Update Base sepolia FP audit fixes upgrade status

tasks/eth/016-granite-protocol-versions/README.md
executed here - https://etherscan.io/tx/0x804fd189aad5c2caccf274235649905f0dd18c8a4f34c58ce471176fec3e34b7
=> update 016 status

tasks/eth/016-granite-protocol-versions/README.md, tasks/eth/018-granite-upgrade/README.md
Just updating some things that have been pointed out by signers:
=> Minor fixes to current tasks

tasks/eth/017-presigned-pause/README.md
This is part of : https://github.com/ethereum-optimism/security-pod/issues/145
=> Update the status of ETH 017 to `SIGNED`

.circleci/config.yml, tasks/eth/base-002-fp-upgrade/README.md
- adding the executing tx
- removing the task from the CI
=> fix: clean up base fp upgrade

.circleci/config.yml, tasks/sep/020-holocene-system-config-upgrade-multi-chain/NestedSignFromJson.s.sol
Add testing file for the task `020-holocene-system-config-upgrade-multi-chain`. 
Also fix a uppercase typo with the lib `stdJson.sol` that has to be `StdJson.sol`. 
I don't know why yet, it was working locally and not into the docker version with the `s` in lower case. 
I guess this is a version issue with forge. 
The error I got was: 
```
file cannot be resolved due to mismatch of file name case: "/root/project/lib/forge-std/src/stdJson.sol": No such file or directory (os error 2).
Found existing file: "/root/project/lib/forge-std/src/StdJson.sol"
Please check the case of the import.
--> /root/project/tasks/sep/020-holocene-system-config-upgrade-multi-chain/NestedSignFromJson.s.sol
forge-std/stdJson.sol
```
I fixed it by: 
```diff
-import {stdJson} from …
```
=> Add Test CI for the task `020-holocene-system-config-upgrade-multi-chain`

.circleci/config.yml, tasks/sep/020-holocene-system-config-upgrade-multi-chain/README.md
I got a bunch os json artifacts in `records/...`: should I commit these?
=> Mark sep/020 task as done

tasks/sep/021-refresh-signers-fakeFoS/README.md, tasks/sep/023-refresh-signers-fakeFuS/README.md, tasks/sep/024-refresh-signers-fakeSC/README.md
Update the status of task `21`, `23`, `24` to `EXECUTED` with the TxHash associated.
**Tests**
**Metadata**
=> Update the status of task `21`, `23`, `24` to `EXECUTED`.

tasks/sep/unichain-001-init-holocene-fp/.env, tasks/sep/unichain-001-init-holocene-fp/README.md, tasks/sep/unichain-001-init-holocene-fp/SignFromJson.s.sol, tasks/sep/unichain-001-init-holocene-fp/VALIDATION.md, tasks/sep/unichain-001-init-holocene-fp/input.json
Resubmitting PR: https://github.com/ethereum-optimism/superchain-ops/pull/409
=> Resubmission: Unichain sepolia init holocene fp

.circleci/config.yml, tasks/eth/022-holocene-fp-upgrade/README.md, tasks/eth/base-003-holocene-fp-upgrade/README.md, tasks/sep/026-fp-holocene-upgrade-fix/README.md
They've all been executed. Also removes CI for Sepolia task.
=> Update executed tasks eth/002, eth/base-003, sep/026

tasks/eth/021-holocene-protocol-versions/README.md
This task was executed so we should mark it as such.
=> fix: updated status of holocene protocol versions update.

tasks/eth/028-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
Some small fixes after reviewing 028 task.
=> fix: 028 task review

foundry.toml, script/DeployRehearsal4.s.sol, script/PresignPauseFromJson.s.sol, script/verification/DisputeGameUpgrade.s.sol, script/verification/Verification.s.sol, tasks/eth/ink-002-set-respected-game-type/SignFromJson.s.sol
Upgrade optimism submodule to develop commit https://github.com/ethereum-optimism/optimism/commit/57fcd5d5492b0645d111de52cf5766809333b7a9
**Tests**
Required to run monorepo upgrade tests against anvil fork where state changes from non terminal tasks have been applied.
**Metadata**
=> feat: upgrade optimism submodule

script/verification/HoloceneSystemConfigUpgrade.s.sol, tasks/sep/028-holocene-system-config-upgrade-and-init-base/SignFromJson.s.sol
Some ready but not-yet-executed tasks depend on this contract, but they are simulated in CI so if that is green should be OK.
=> push codeExceptions exceptions into HoloceneSystemConfigUpgrade contract

tasks/sep/028-holocene-system-config-upgrade-and-init-base/README.md, tasks/sep/028-holocene-system-config-upgrade-and-init-base/SignFromJson.s.sol, tasks/sep/028-holocene-system-config-upgrade-and-init-base/VALIDATION.md, tasks/sep/028-holocene-system-config-upgrade-and-init-base/input.json
Follows https://github.com/ethereum-optimism/superchain-ops/pull/476 to update the EIP1559 parameters to `_denominator = 250` and `_elasticity = 4`.
=> sep/028: update EIP1559 parameters

runbooks/mcp-to-permissioned-fps-1.6.0.md
Minor cleanup/fixes in the runbook so that I can use it for 1.8.0
=> feat: clean up fp 1.6.0 runbook

src/improvements/single.just, src/improvements/task/MultisigTask.sol, test/task/SingleMultisigTask.t.sol
Add `single.just` in improvements directory with intentions to replace the original `single.just` file in future.
**Metadata**
Resolves https://github.com/ethereum-optimism/superchain-ops/issues/473 partially
=> [FPS] add single just file for improvements

.circleci/config.yml
- Step 1: Publish and test with dev orb ✅ 
- Step 2: Publish and test with prod orb. ✅ 
Related Orb PR: https://github.com/ethereum-optimism/circleci-utils/pull/7 
Closes: https://github.com/ethereum-optimism/superchain-registry/issues/892
=> Orbify Mise

src/improvements/AddressRegistry.sol, test/registry/AddressRegistry.t.sol, test/tasks/mock/DiscoverChainAddressesConfig.toml
Related to: https://github.com/ethereum-optimism/superchain-ops/pull/565
Opting to take the approach of using low-level calls and checking return data to make sure that a contract call occurred as expected.
=> Discovery bug: try/catch not working for addresses with no code.

.circleci/config.yml
closes: https://github.com/ethereum-optimism/superchain-ops/issues/580
=> slack notifications for CI tasks

.circleci/config.yml, src/improvements/script/check-superchain-latest.sh
Reverts ethereum-optimism/superchain-ops#586
=> Revert "Bm/test fail scr checks"

tasks/sep/030-revert-mt-cannon/README.md
=> Mark sep/030 as executed

src/improvements/script/create-template.sh, src/improvements/template/DisputeGameUpgradeTemplate.sol, src/improvements/template/GasConfigTemplate.sol, src/improvements/template/SetGameTypeTemplate.sol
Revert on default template that is created via `just new template`. Also, removing a bunch of unused imports.
=> Create new template cleanup

.circleci/config.yml, tasks/sep/zora-002-fp-upgrade/README.md
- Updating zora-002 task status to executed and linking the executing tx
- Removing the task from the CI
=> zora-002 has been executed

nested.just, security-council-rehearsals/2024-01-22-r2-remove-signer-0122/justfile, security-council-rehearsals/templates/r2-remove-signer/justfile, single.just, src/improvements/tasks/TaskRunner.sol
Some PR comments that I was keeping track of in a personal TODO list addressed here. Small things like removing logs and adding comments.
=> fix: Misc PR comments addressed.

src/improvements/tasks/MultisigTask.sol
This removed code duplication and relies on a new library that was built specifically for this task. Closes: https://github.com/ethereum-optimism/superchain-ops/issues/613
=> feat: Integrating new state diff decoding tool

.circleci/config.yml, tasks/sep/ink-001-fp-holocene-pectra-upgrade/README.md
ink-001 executed 
https://sepolia.etherscan.io/tx/0xc79c08b4f417db62e1cf7561352ae2b9cd123e4573a1a4b6b62dcbb0ae5049de
=> executed ink-001

.circleci/config.yml, .gitignore, script/utils/sim-sequence.sh
To sum up this short PR adds: 
- Added the support for Sepolia Sim Sequence.
- Added checks that `.env` file of the tasks simulated is correct to enforce more and avoid nonce issue that we had in the past with `SAFE_NONCE` instead of `SAFE_NONCE_XXXX`
- Fix the issue that Anvil was staying in background for ever (#646)
- Added the simulation of the task 30 for now. Since this is the **only** one merged of the sequence of the  _Superchain Version Sync_ 
PS: Once done, we should also add this to each tasks into each new PRs created like (031, 032, ..etc). 
**Tests**
I did bunch of tests locally and this is producing the expect  output with sep, and eth tasks.
**Metadata**
=> [SIMULATION] Sequence Superchain Version Sync Tasks

.circleci/config.yml, tasks/sep/ink-002-holocene-system-config-upgrade/README.md
=> ink sepolia 002 executed

tasks/sep/032-op-pectra-defence/VALIDATION.md
Fixes the message hash in VALIDATION.md
=> fix incorrect message hash

.circleci/config.yml, tasks/sep/032-op-pectra-defence/README.md
Add tx link to U12 execution on OP Sepolia, and fix a typo.
=> Update status of sep-32

script/utils/sim-sequence.sh
This PR introduce, a new display function to show inconsistency between the env and on-chain. 
If there is no inconsistency this will show the env + onchain nonce to help people to debug in case of nonce failure.
=> [SIMULATION-SEQUENCE] Add new display function 

.circleci/config.yml, tasks/eth/ink-003-fp-holocene-pectra-upgrade/README.md
=> Set the status of ink-003 to EXECUTED

.circleci/config.yml, tasks/sep/033-op-pectra-defense/README.md
=> Update sep/033 task status

.circleci/config.yml, tasks/eth/unichain-001-holocene-systemconfig-update/README.md
Update the status of the task Uni-001 to executed and also fix the Ci accordingly.
=> Change status to Executed Uni-001.

src/improvements/tasks/MultisigTask.sol, src/improvements/tasks/StateOverrideManager.sol, src/libraries/GnosisSafeHashes.sol, test/libraries/GnosisSafeHashes.t.sol, test/tasks/StateOverrideManager.t.sol
As per [this discussion](https://discord.com/channels/1244729134312198194/1348735037754839113/1351623170796294174) in discord, we realized that a regression exists in the `NESTED.md` signing flow. Signers domain and message hashes do not appear in Tenderly. We want to keep this functionality as this is what signers are familiar with.
The high level changes are, for **_nested_** simulations:
1. Make sure the simulation is executed through the MultiCall3 contract. 
2. Make the Multicall3 contract the owner on the child multisig
3. Execute the first `Mulitcall3` action: `approveHash` (via child multisig execution)
4. Execute the second `Multicall3` action: `execTransaction` (works because parent multisig already has the approval)
I'd like to get some feedback on whether or not the output of …
=> refactor: Nested Simulations in Tenderly Should Originate from MultiCall3

src/improvements/tasks/sep/000-opcm-upgrade-v200/VALIDATION.md
Updates the council message hash to match what John and Matt both see. 
Will check with Blaine about it on Monday.
=> Update message hash

src/improvements/tasks/MultisigTask.sol
Feature flagging op-txverify feature until U13 is fully executed.
=> fix: Temporary feature flag around op-txverify feature.

script/PresignPauseFromJson.s.sol, script/verification/DisputeGameUpgrade.s.sol, src/libraries/Utils.sol, test/libraries/Utils.t.sol
create utils library and isFeatureEnabled helper function, add test for it
=> isFeaturedEnabled helper

src/improvements/single.just, src/improvements/tasks/sep/003-unichain-superchain-config-fix/README.md
Building on this PR: https://github.com/ethereum-optimism/superchain-ops/pull/800 
I don't want the single simulate command to include a breaking change.
=> fix: single simulate should not have breaking change

.circleci/config.yml
To avoid non-terminal tasks having errors on main we should run CI checks against them
=> fix: run pending u13 tasks in ci.

src/improvements/tasks/MultisigTask.sol
The idea is to check the code size of the parent multi-sig to avoid failing after with no clear revert when we get the nonce of the safe. 
Before:
After: 
So now we can clearly see that the parent multisig is not deployed (often wrong chain address usage). 
We should also the same for the child safes in the future or in this PR.
=> check the size of the parent multisig before continuing.

src/improvements/tasks/MultisigTask.sol
Reverts ethereum-optimism/superchain-ops#809
=> Revert "check the size of the parent multisig before continuing."

src/improvements/tasks/sep/003-unichain-superchain-config-fix/README.md
=> update executed status

.circleci/config.yml, src/improvements/tasks/sep/003-opcm-upgrade-v200/README.md, test/tasks/example/sep/004-replace-superchain-config/.env
=> Unichain Sepolia Upgrade 13 executed

src/improvements/tasks/MultisigTask.sol, src/improvements/tasks/StateOverrideManager.sol, test/tasks/StateOverrideManager.t.sol
Improved handling of nested multisig transactions by properly tracking and managing nonces for both parent and child multisigs.
- Added dedicated storage for child multisig address and nonce
- Refactored `_taskSetup` to capture both parent and child nonce values
- Removed redundant nonce state overrides in Tenderly simulations
- Simplified function signatures by using stored child multisig information instead of passing it as parameters
- Created a new `_nonceBeforeSim` helper function to correctly retrieve nonces before simulation
- Consolidated print functions to use stored child multisig data
- Improved code organization and documentation for nested multisig operations
1. Run an existing non-terminal task
2. Check the hashes match VALIDATION file.
3. Check that the Tenderly simulation …
=> refactor: improve nested multisig task handling

.circleci/config.yml
This PR add the task in the CI for `/sep/004-deputy-pause-module-activation`.
=> [DeputyPauseModule] Activation task added to CI

.circleci/config.yml, src/improvements/tasks/sep/008-deputy-pause-key-rotation/README.md
Mark as executed the task-008 `DeputyRotationKey`
=> Mark as executed the task-008 DeputyRotationKey. 

.circleci/config.yml, src/improvements/tasks/sep/004-deputy-pause-module-activation/README.md
Set the Deputy Pause Module Task 004 set as **Executed**
=> Mark task 004 Deputy Pause Module Activation

src/improvements/tasks/eth/004-opcm-upgrade-v300-base/VALIDATION.md
Adds missing content to the Base U14 runbook.
=> Add missing diffs

src/improvements/nested.just, src/improvements/single.just, src/improvements/tasks/MultisigTask.sol, src/libraries/AccountAccessParser.sol, tasks/eth/zora-002-fp-upgrade/NestedSignFromJson.s.sol, test/libraries/AccountAccessParser.t.sol
See description on: https://github.com/ethereum-optimism/superchain-ops/pull/912
=> fix: Log more info for approve hash writes and make signers output cleaner.

.circleci/config.yml, src/improvements/tasks/eth/003-opcm-upgrade-v300-op-ink-soneium/README.md, src/improvements/tasks/eth/004-opcm-upgrade-v300-base/README.md, tasks/eth/zora-002-fp-upgrade/README.md
Executed 2 U14 tasks. Still waiting on unichain. Also executed Zora upgrade.
=> fix: updating state of executed tasks.

.circleci/config.yml, src/improvements/tasks/StackedSimulator.sol, src/improvements/tasks/TaskManager.sol, test/tasks/StackedSimulator.t.sol
This fixes the currently failing CI we're seeing on the main branch.
=> fix: fixing failing ci on main - related to stacked simulations.

.circleci/config.yml, src/improvements/tasks/eth/005-opcm-upgrade-v300-uni/README.md
Marking task as executed and removing CI job.
=> fix: Unichain U14 Executed

src/improvements/tasks/eth/009-opcm-update-prestate-v300-op+ink/009-report.md, src/improvements/tasks/eth/010-opcm-update-prestate-v300-uni/010-report.md
This PR adds Spearbit's audit reports for Optimism Upgrade Proposal #15a, covering:
009-report.md: Review of opcm-update-prestate-v300-op+ink
010-report.md: Review of opcm-update-prestate-v300-uni
=> Spearbit: Optimism Upgrade Proposal #15a Review

src/improvements/tasks/eth/010-opcm-update-prestate-v300-uni/README.md
=> fix: Unichain U15 ready to sign

README.md, src/improvements/template/boilerplate/L2TaskBase.template.sol, src/improvements/template/boilerplate/OPCMTaskBase.template.sol, src/improvements/template/boilerplate/SimpleTaskBase.template.sol
Adding some clarity around the new and old superchain-ops system. This will hopefully steer folks in the right direction when going to create a new task.
=> docs: add clarity around new and old system

tasks/eth/arena-z-001-fp-holocene-upgrade/README.md
Updating the Status of Arena-Z task 001
=> Arena-Z 001 README.md status update

src/improvements/tasks/MultisigTask.sol, src/improvements/tasks/types/L2TaskBase.sol, src/improvements/template/boilerplate/L2TaskBase.template.sol, src/improvements/template/boilerplate/OPCMTaskBase.template.sol, src/improvements/template/boilerplate/SimpleTaskBase.template.sol, test/tasks/MultisigTask.t.sol, test/tasks/mock/MockTarget.sol
should be merged into branch [jb/balance-changes](https://github.com/ethereum-optimism/superchain-ops/tree/jb/balance-changes)
=> fix: fixing tests and refactoring

src/improvements/README.md
Forgot to put the mise trust and install step in.
=> docs: mise install additions

src/improvements/tasks/MultisigTask.sol, src/improvements/template/OPCMUpgradeV400.sol, test/libraries/AccountAccessParser.t.sol
Added more tests for the most recent getEthTransfers function updates.
=> fix: getETHTransfers testing

.circleci/config.yml, tasks/eth/arena-z-001-fp-holocene-upgrade/README.md, tasks/eth/swell-001-holocene-upgrade/README.md
set to executed tasks that got executed today.
=> Mark as executed arena-z + swell 

src/improvements/tasks/StackedSimulator.sol
You can test this works by:
```bash
cd src/improvements
just simulate-stack sep 015-opcm-upgrade-v400-uni-soneium
```
=> fix: Refresh task config after each stacked simulation is executed.

src/libraries/MultisigTaskPrinter.sol
Small fixes, required for work with nested multisigs.
=> fix: small tweaks required for nested multisigs

src/improvements/tasks/MultisigTask.sol
Fixing a bug that broke tenderly simulations for nested tasks.
=> fix: Tenderly sims fix

src/improvements/tasks/sep/013-l1-ownership-transfers-uni/config.toml
Makes space for the challenger transfer task.
=> bump the uni PAO transfer nonce

CONTRIBUTING.md
Just a few typos I found on the root CONTRIBUTING.md
=> docs: small fixes to CONTRIBUTING.md at root

tasks/sep/metal-002-fp-upgrade/README.md
=> Update Metal Sepolia FP Task Status

tasks/sep/mode-002-fp-upgrade/README.md
Update Task Status to READY TO SIGN
=> Update Mode Sepolia FP Task Status

.circleci/config.yml, tasks/sep/metal-002-fp-upgrade/README.md, tasks/sep/mode-002-fp-upgrade/README.md
Update Mode and Metal Sepolia FP Tasks Status and remove CI job
=> Update Mode and Metal Sepolia task status and CI

tasks/eth/metal-002-fp-upgrade/VALIDATION.md, tasks/eth/mode-002-fp-upgrade/VALIDATION.md
Updating the Metal and Mode FP upgrade hashes to the correct ones
=> Fix Metal/Mode hash messages

nested.just, single.just, src/improvements/nested.just, src/improvements/single.just
Reverts ethereum-optimism/superchain-ops#1089
=> Revert "feat: add trezor support"

src/improvements/tasks/sep/014-U16-opcm-upgrade-v400-op-ink/VALIDATION.md
Adds detailed validation entries for the updated Op and Ink contracts (276-354).
=> Add in outline of state diff for 014 runbook

src/libraries/AccountAccessParser.sol
No need to call `getStateDiffFor` twice, we can call it once and reuse later.
=> perf(decode): Small performance improvement for decoding state diffs

security-council-rehearsals/rehearsal-3-nested-upgrade/README.md, src/improvements/README.md, src/improvements/tasks/eth/rehearsals/2025-07-31-R3-nested-upgrade/README.md
Last rehearsal task executes in the batch of three for Aug 2025. Some documentation updates.
=> feat: update rehearsal three - 2025

test/tasks/example/sep/025-opcm-upgrade-superchainconfig-v410/config.toml
cleanup upgrade superchainConfig example task
=> cleanup upgrade superchainConfig example task

README.md
=> doc: mise activate instruction

src/tasks/sep/028-U16a-opcm-upgrade-v410-unichain/README.md
set unichain u16a sep executed
=> set unichain u16a sep executed

src/tasks/eth/023-U16a-opcm-upgrade-v410-op-soneium-ink/README.md, src/tasks/eth/024-U16a-opcm-upgrade-v410-unichain/README.md
Update commands so they're correct for signers and facilitators.
=> docs: README commands updated - Uni U16a

src/tasks/sep/030-zora-sep-u13-to-u16a/README.md, src/tasks/sep/031-metal-sep-u13-to-u16a/README.md, src/tasks/sep/032-mode-sep-u13-to-u16a/README.md, src/tasks/sep/033-arena-z-u15-to-u16a/README.md
Updating Sepolia tasks status to executed with etherscan links
=> Update sepolia tasks status

README.md, src/libraries/MultisigTaskPrinter.sol, src/tasks/MultisigTask.sol, src/template/boilerplate/VALIDATION.template.md
Addressing feedback given in https://github.com/ethereum-optimism/superchain-ops/issues/1224.
=> fix: Feedback from #1124 addressed
