ethereum-optimism/superchain-ops

- justfile
- script/NestedSignFromJson.s.sol
- script/SignFromJson.s.sol
- src/JsonTxBuilderBase.sol
since they are needed by security council as well, not just the developers.
> Merge install-dev-contracts to install

- security-council-rehearsals/templates/r1-hello-council/README.md
Originally, we recommend an M-of-2M multisig to be created by the facilitator for the security council rehearsal multisig, but in rehearsal 2, we will be removing one signer, so we should recommend an M-of-(2M+1) multisig to start with so after the signer removal rehearsal, the facilitator still hold enough keys to reach a quorum.
> Security council rehearsal: recommend an M of 2M+1 multisig

- tasks/eth/0-pause-mainnet/README.md
to signify that this is not yet ready to sign by the signers. We need to 
1. get Foundation written approval
2. use the latest nonce
> Add "Status: DRAFT, NOT READY TO SIGN" to 0-pause-mainnet

- tasks/eth/3-add-superchainConfig/README.md
- tasks/eth/3-add-superchainConfig/Validation.md
1. Updates the status to Ready to sign
2. Fixes some whitespace for readability
3. Adds the vote link
> Finalize Upgrade #4 status

- tasks/eth/004-add-superchainConfig/Validation.md
This removes a step which validated the nonce change in the Foundation Safe which previously acted as the ProxyAdmin owner. It should have been removed when the runbook was updated for the nested 2 of 2 safe. This new Safe uses a different foundation Safe, so the `0x9ba...` address should not appear at all in the state diff.
It also fixes a link that pointed to the wrong location in the monorepo.
> Remove outdated Foundation Safe validation step

- NESTED.md
- SINGLE.md
- tasks/eth/005-protocol-versions-ecotone/README.md
Fixes: 
1. Some outdated text in the 005 runbook
2. Some typos in the SINGLE and NESTED documents
> Fixes to 005 runbook

- tasks/eth/006-MCP-L1/README.md
- tasks/eth/006-MCP-L1/VALIDATION.md
- The link to the validation file did not reliably work in the GitHub UI for me
- Storage key updates from https://github.com/ethereum-optimism/superchain-ops/pull/110 that were missed
> fix: key updates, github links are case sensitive

- nested.just
- single.just
Enables the ability to not use a ledger when
the env var `SIMULATE_WITHOUT_LEDGER` is set.
It just needs to be set to anything to work
> feat: configurable no ledger usage

- tasks/eth/005-3-ecotone-calldata-gas-config/README.md
- tasks/eth/005-protocol-versions-ecotone/README.md
This looks like the correct transaction based on it's calldata: https://etherscan.io/tx/0x29bb617fac8f49f5c934cc776b22d47e187ab482e86f21e4502a23ba1c9ad0da
First decoding the `data` from the root level input data
```
$ cast 4byte-decode 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001000000000000000000000000008062abc286f5e7d9428a0ccb9abd71e50d93b9350000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000245fd579af0000000000000000000000000000000000 …
```
> mainnet: update task 005 to executed status, add tx hash

- tasks/sep/003-MCP-L1/README.md
Updates the status of the MCP L1 upgrade on Sepolia. I found this transaction hash manually and based on the state changes it seems correct, but the reviewer should confirm before merging
I left the "governance vote" section alone since that is placeholder text and we don't need governance approval for testnet upgrades
> tasks(sep-mcpL1): update status

- tasks/eth/mode-001-MCP-L1/.env
Last rpc url wasn't an archive node so ci wasn't working.
> fix: adding archive node for mode.

- src/JsonTxBuilderBase.sol
- tasks/eth/006-MCP-L1/NestedSignFromJson.s.sol
related to foundry vm issues during delegate call (wrong accessor)
> fix: account checks using old and new balances instead of final balance

- tasks/sep/006-1-sc-changes/VALIDATION.md
When we updated the addresses of the modules, the resulting keys of the modules mapping were changed in Validation.md
This fixes the keys, and reorders them to match the display in Tenderly.
The nonce on the `FakeSecurityCouncil` was also different from the nonce on the `TestFakeSecurityCouncil`.
> Fixes to storage keys in Validation.md

- README.md
Updates the readme to document the requirement of implementing
the `_postCheck` hook so that we can rely more on automation
of checking the correctness of upgrade scripts
> readme: note some info on adding a task

- .circleci/config.yml
- .gitignore
- PRESIGNED-PAUSE.md
- presigned-pause.just
- tasks/sep/009-presigned-pause/.env
- tasks/sep/009-presigned-pause/README.md
- tasks/sep/009-presigned-pause/input.json
- tasks/sep/009-presigned-pause/tx/draft-16.json
- tasks/sep/009-presigned-pause/tx/draft-17.json
- tasks/sep/009-presigned-pause/tx/draft-18.json
- tasks/sep/009-presigned-pause/tx/draft-19.json
- tasks/sep/009-presigned-pause/tx/draft-20.json
- tasks/sep/009-presigned-pause/tx/draft-21.json
In [this Sepolia transaction](https://sepolia.etherscan.io/tx/0x3d2b9d3e6aaf9f436f05d47c7ae547a3202132ae927966d8fc95c6277d4246b0), we removed the `DeputyGuardianModule` in preparation for setting up the 1 of 1 Guardian Safe.
This invalidated the presigned pauses from [008-presigned-pause](../008-presigned-pause/README.md). 
This playbook is for generating new presigned pauses, which have the Sepolia Foundation Safe directly call the SuperchainConfig
> task: add Sepolia 009 Presigned Pause Ceremony 

- tasks/eth/013-fp-upgrade-fjord/.env
- tasks/eth/013-fp-upgrade-fjord/VALIDATION.md
Adjust the expected nonce of the Foundation safe to make room for the 11-3 upgrade.
> mainnet-013: Update nonce to accomodate 11-3

- nested.just
Prior to this change, the output of running the nested simulation was, unclear about 
which account was being used to sign.
```
➜ just \
--dotenv-path $(pwd)/.env \
--justfile ../../../nested.just \
simulate foundation
Running script with assertions
Using script /Users/maurelian/projects/o/superchain-ops.1/tasks/eth/base-001-MCP-L1/NestedSignFromJson.s.sol
getting signer address for foundation...
signer: 0x42d27eEA1AD6e22Af6284F609847CB3Cd56B9c64 # signer?
safe: 0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A
Simulating call to foundation at 0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A
Simulating with ledger account: 0x1084092Ac2f04c866806CF3d4a385Afa4F6A6C97  #signer?
```
> Remove confusing additional echo statement

- src/JsonTxBuilderBase.sol
Reverts a change made in #238.
`checkStateDiff` should be virtual to enable wholistic state diff checks like [used here](https://github.com/ethereum-optimism/superchain-ops/blob/maur/restore-virtual/tasks/eth/010-1-guardian-upgrade/NestedSignFromJson.s.sol#L97).
> Make checkStateDiff virtual

- .circleci/config.yml
Refactors CI to a single `main` workflow, similar to what we have in the monorepo. This makes it easier to add new jobs to CI and have them automatically required as passing before merging PRs. With the current approach, we have to go into settings and add each new workflow as a required status check. With this approach, we add `main` as the only required status check.
I also added a check to fail on solc warnings. This won't do much due to our nonstandard repo structure so not everything compiles by default, but it we should gradually move to a more standard structure over time
> ci: refactor to a single workflow

- script/DeployRehearsal1.s.sol
- security-council-rehearsals/templates/r1-hello-council/justfile
Follows the rehearsal deploy script convention set in #262. 
Note: There are no deploy scripts for R2, and R3 does not exist (for reasons I don't clearly recall at this point). So this covers all rehearsal deploy scripts, and helps prepare for #239.
> Rename DeployHelloWorld to DeployRehearsal1

- .circleci/config.yml
- tasks/eth/mmz-002-key-handover/README.md
Conduit has executed the Key Handover for Mode, Metal, and Zora: https://etherscan.io/tx/0xf4e7778523991cf6c4b305970c2c9e71ef27f652e475bb42302d582fa613f5a3
> updating 002-mmz-key-handover status

- tasks/sep/013-fp-granite-prestate/NestedSignFromJson.s.sol
- tasks/sep/013-fp-granite-prestate/README.md
- tasks/sep/013-fp-granite-prestate/VALIDATION.md
- tasks/sep/013-fp-granite-prestate/input.json
Updates the `op-program` tag to `op-program/v1.3.0-rc.3` for the Sepolia prestate upgrade task.
> update: Sepolia prestate `op-program` tag

- tasks/sep/014-fallback-permissioned-game/README.md
This PR set the README of the task 014-fallback-permissioned-game to `CANCELLED` on Sepolia as we decided to not go through this process.
> set the README of the task 014-fallback-permissioned-game to `CANCELLED`.

- tasks/eth/015-fallback-permissioned-game/README.md
The mainnet fallback was executed last Friday via https://etherscan.io/tx/0x493e2f3354e8c6c46fb37925a13c02364c1f3b38f88548b9bb4673e3fc762e69
> Update mainnet FP fallback task status

- tasks/sep/017-presigned-pause/tx/draft-0.json
- tasks/sep/017-presigned-pause/tx/draft-1.json
- tasks/sep/017-presigned-pause/tx/draft-2.json
- tasks/sep/017-presigned-pause/tx/draft-3.json
- tasks/sep/017-presigned-pause/tx/draft-4.json
This is adding the `tx/` folder with the `draft-X.json` transaction. 
This is going to be useful to ONLY use the command  `sign` for the signers like below otherwise this is required to make the `prepare` for each signers.
```
just \
--dotenv-path .env \
--justfile ../../../presigned-pause.just \
sign 
```
> Add `draft-X.json` into the `tx/` folder. 

- NESTED.md
- PRESIGNED-PAUSE.md
- SINGLE.md
- justfile
Signers often run into the following error if a script has been removed since they last built:  
```
failed to read artifact source file for `/Users/maurelian/projects/o/superchain-ops/script/PresignPauseFromJson_eth_008.s.sol`
```
This is meant to address that.
> feat(docs): enhance setup instructions with shell code blocks

- .circleci/config.yml
- presigned-pause.just
- tasks/eth/017-presigned-pause/PresignPauseFromJson.s.sol
- tasks/eth/017-presigned-pause/tx/draft-100.json
- tasks/eth/017-presigned-pause/tx/draft-101.json
- tasks/eth/017-presigned-pause/tx/draft-102.json
- tasks/eth/017-presigned-pause/tx/draft-103.json
- tasks/eth/017-presigned-pause/tx/draft-104.json
- tasks/eth/017-presigned-pause/tx/draft-95.json
- tasks/eth/017-presigned-pause/tx/draft-96.json
- tasks/eth/017-presigned-pause/tx/draft-97.json
- tasks/eth/017-presigned-pause/tx/draft-98.json
- tasks/eth/017-presigned-pause/tx/draft-99.json
This PR modify the usage of the script used (`PresignPauseFromJson`) during the usage of the `presigned-pause.just`
Now, this will create custom script into the task directory directly exactly like the other standard tasks that are using the `single.just` (cf screenshot of the single tasks here):
For now, if we need to overrides a PresignedPause task we have to create the file at the into `script/` that is not ideal and  would need to be removed after the task (i.e task [eth_017](https://github.com/ethereum-optimism/superchain-ops/pull/314/files) or task [eth_008](https://github.com/ethereum-optimism/superchain-ops/pull/220/files)) to clean up the repository..
Now, with this PR we can use the script directly into the same folder like this:
**Tests**
I have test using the …
> WIP:Fix the `SCRIPT` PATH For the PresignedPause justfile 

- script/NestedSignFromJson.s.sol
Implemented the `_nestedPostCheck` function in the `NestedSignFromJson` base script.
This provides a robust fix to the failed simulation on approval calls.
Keeping in draft until #311 is merged to not break it.
> Add _nestedPostCheck to NestedSignFromJson base script

- presigned-pause.just
This is a small PR that adding the command `save-PSPs` into the Just file for the PSPs. 
https://github.com/user-attachments/assets/46a4a218-920c-4ef7-b75e-7a881d801933
As `op-defender` is taking in input a array of PSPs in JSON format as per the documentation here:
https://github.com/ethereum-optimism/monitorism/blob/main/op-defender/psp_executor/README.md#1-usage
I think would be nice to be capable to use the same `just` file with the same commands for sake of consistency and speed, after the PSPs are merged and simulated. 
I will update the internal documentation for `op-defender` and the PresignedPause runbook. 
**Tests**
I have performed this tests locally. 
**Metadata**
This is part of https://github.com/ethereum-optimism/security-pod/issues/147
> add: `save-PSPs` feature into the `presigned-pause.just`

- PRESIGNED-PAUSE.md
This PR include the informations in case an upgrade cause the changes to break the PSPs.
In the future, this will be less the case to happen since we will make the DGM proxify. 
As part of the design review for upgrading the DGM here (https://github.com/ethereum-optimism/design-docs/pull/89)
**Tests**
**Metadata**
> Update `PRESIGNED-PAUSE.md` with the GAP disclaimer.

- tasks/eth/base-002-fp-upgrade/VALIDATION.md
This _PR_ fix the value with the correct nonce value (accordingly with the data onchain of the FoS). 
```diff
-The nonce (slot 0x5) should be increased from 94 to 95.
+The nonce (slot 0x5) should be increased from 95 (0x5F) to 96 (0x60).
```
> Fix nonce values into the base-upgrade-mainnet-faultproof tasks. 

- tasks/sep/fp-recovery/005-set-game-implementation/README.md
- tasks/sep/fp-recovery/005-set-game-implementation/justfile
- tasks/sep/fp-recovery/005-set-game-implementation/templates/NestedSignFromJson.s.sol
- tasks/sep/fp-recovery/005-set-game-implementation/templates/VALIDATION.md
- tasks/sep/fp-recovery/005-set-game-implementation/templates/tx/setAnchorState.json
Adds an additional transaction template to https://github.com/ethereum-optimism/superchain-ops/pull/363 that re-initializes the `AnchorStateRegistry` to add an initial anchor state for new game types.  The initial anchor state to use is taken from the current anchor state for another game type (at the time the `just` command is run so it's static in the resulting task definition).
This allows creating a task to enable permissionless fault proofs on a chain that previously only deployed permissioned games.
> Add ability to re-initialize AnchorStateRegistry with additional game types

- NESTED.md
- nested.just
As per the title, we want to add the ability for the L1 ProxyAdmin owner to be a 3-of-3 safe as well as a 2-of-2 safe. Some chains require an additional wallet in their L1PAO.
> 3-of-3 Proxy Admin Owner Support: Chain governor able to sign for nested safes

- tasks/sep/020-holocene-system-config-upgrade-multi-chain/VALIDATION.md
@geoknee Discover and Inform me of an inconsistency between the `approveHash` storage calculation from the task `020-holocene-system-config-upgrade-multi-chain`. 
After investigation, I missed the change of `nestedHash` value (so the value were calculated on the incorrect value but were matching the `VALIDATION.md` file that has incorrect values...).
Now, the value are matching the simulation correctly for example for security council below:
**State Precomputed**
**Tenderly Simulation**
> Fix `ApprovalHash` Incorrect Storage of task `020-holocene-system-config-upgrade-multi-chain`

- LICENSE
Adds the same MIT license as the monorepo https://github.com/ethereum-optimism/optimism/blob/develop/LICENSE
> doc: add license

- tasks/sep/base-003-fp-granite-prestate/README.md
This [task](https://github.com/ethereum-optimism/superchain-ops/pull/295) was never marked as executed.
This is part of a wider effort to make sure all tasks are in the correct state so that we can run simulate and have expected results as per this pr: https://github.com/ethereum-optimism/superchain-ops/pull/391
> Executed: Sepolia FP Upgrade - Granite Prestate Update

- tasks/sep/013-fp-granite-prestate/README.md
Similar to this recently merged [PR](https://github.com/ethereum-optimism/superchain-ops/pull/419), this task _was_ executed but never had it's README.md file updated.
> FP Task should have been marked as executed

- .circleci/config.yml
- NESTED-VALIDATION.md
- script/verification/CouncilFoundationNestedSign.s.sol
- script/verification/DisputeGameUpgrade.s.sol
- script/verification/Verification.s.sol
Developed in #421 and now split into its own PR.
> Add verification framework & FP dispute game module

- runbooks/key-handover.md
Replaced requirement with **requirements**, as the sentence should use the plural form to agree with "One of the".
> docs: typo fix Update key-handover.md

- justfile
Bump to https://github.com/base-org/eip712sign/releases/tag/v0.0.10, which fixes signing with ledgers with the latest firmware version, and also supports Ledger Flex.
**Tests**
Tested locally.
Signers were having trouble after updating to the latest ledger firmware. Upstreamed a fix to go-ethereum here: https://github.com/ethereum/go-ethereum/pull/31004/files.
> Bump to latest eip712sign version

- tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
Discovered when running through the validation.
> sep/027: recompute `approvedHashes` keys

- .circleci/config.yml
Simulat ci task added for: https://github.com/ethereum-optimism/superchain-ops/tree/main/tasks/eth/029-holocene-system-config-upgrade-and-init-base
This wasn't added in the original PR.
> Add simulate task for eth/029

- test/task/Regression.t.sol
Add regression tests for current fps tasks. Check that the data to sign and the calldata generated from the tooling at a particular block matches with hardcoded values. These tests will make sure that the tooling updates in the future do not generate wrong datas.
**Metadata**
- Fixes https://github.com/ethereum-optimism/superchain-ops/issues/481
> add regression tests

- justfile
- script/DeployMulticall3Delegatecall.sol
- src/Multicall3Delegatecall.sol
Adds Multicall3Delegatecall. The contract is based heavily on Multicall3 deployed on many evm chains at 0xcA11bde05977b3631167028862bE2a173976CA11. It has been modified to:
1. Perform delegatecalls instead of calls.
2. Utility getter functions have been removed.
This contract will be deployed to [0x242a28aae0df515cefd09984f3057b3621646e9a](https://sepolia.etherscan.io/address/0x242a28aae0df515cefd09984f3057b3621646e9a).
> feat: Add Multicall3Delegatecall.sol

- .circleci/config.yml
- foundry.toml
- src/fps/AddressRegistry.sol
- test/task/NestedMultisigTask.t.sol
Small code changes to allow compiling without via-ir, reduces build time from over 5 minutes to <2s. Via-ir is very slow when doing a lot of struct operations
Also removes extra slashes that were appended to a lot of comments
Partially resolves #512
> perf: reduce build time

- tasks/eth/029-holocene-system-config-upgrade-and-init-base/VALIDATION.md
Fix state validation for SystemConfigProxy (`0x73a79Fab69143498Ed3712e519A88a918e1f4072`) due to the recent gas target bump on Base.
> eth/029: fix validation previous value

- .circleci/config.yml
This task was executed (see [here](https://github.com/ethereum-optimism/superchain-ops/pull/543)). Removing the CI task.
> fix: remove outdated ci task.

- src/improvements/justfile
Before, this command would leave allocs.json lying around in `lib/optimism/packages/contracts-bedrock/allocs.json`. This PR cleans it up after use.
> fix: Clean up monorepo justfile command

- tasks/sep/fp-recovery/005-set-game-implementation/justfile
The -j flag in the sep/fp-recovery/005-set-game-implementation/justfile causes a parsing error (possibly deprecated, misinterpreted or conflicting with another flag). Changing it to --json resolves the issue and correctly retrieves the expected JSON output.
> FIX: replace -j flag with --json in sep/fp-recovery/005/justfile

- src/improvements/AddressRegistry.sol
- src/improvements/IAddressRegistry.sol
- test/registry/AddressRegistry.t.sol
Add a getter function in address registry that returns info corresponding to an address. It return the address identifier and a chain info struct which contains l2chain name and l2chain id.
**Tests**
Updated tests for the happy path and for the revert path.
**Metadata**
[reference](https://discord.com/channels/1244729134312198194/1327372079380824267/1339085947169411204)
> add getter for address info

- .circleci/config.yml
- src/improvements/justfile
Recent CI failure has shown our error logging isn't enough: https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-ops/3479/workflows/7e3d0fc2-2f83-4fac-a68e-0b61cd8a7afe/jobs/38952
> fix: verbose logging on monorepo-integration-tests with rerun

- .circleci/config.yml
- foundry.toml
We have failing CI pipelines in superchain-ops: https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-ops 
All pipelines that are failing fail at the `forge test`, `simulate` or `simulate-nested` step. 
I've moved the internal addresses to the `foundry.toml` file. The thought process here is that we can eventually remove references to them in the circleci yml file. In the meantime, we will rely on foundry profiles to make sure the correct rpc's are used.
> fix: using internal rpc urls for forge test

- .circleci/config.yml
When using mise in the repo it reach unauthenticated requests to GitHub rate limit. To overcome the issue we added a readonly GITHUB_TOKEN that will be used for the requests. 
```
WARN  GitHub rate limit exceeded. Resets at 2025-02-20 04:52:17
WARN  GitHub API returned a 403 Forbidden error. This likely means you have exceeded the rate limit.
WARN  GITHUB_TOKEN is not set. This means mise is making unauthenticated requests to GitHub which have a lower rate limit.
To increase the rate limit, set the GITHUB_TOKEN environment variable to a GitHub personal access token.
Create a token at https://github.com/settings/tokens and set it as GITHUB_TOKEN in your environment.
You do not need to give this token any scopes.
```
**Tests**
**Metadata**
> Add readonly public repo token context

- mise.toml
- test/libraries/BytecodeComparison.t.sol
Foundry 1.0.0 is out, and this repo is an easier place to test the upgrade than the monorepo.
To allow the existing tests to pass, it was chosen to allow `expectRevert` to catch reverts from internal functions, instead of the more convoluted route of creating a helper contract. From [here](https://book.getfoundry.sh/guides/v1.0-migration#expect-revert-cheatcode-disabled-on-internal-calls-by-default).
**Tests**
Compared to `nightly-5d16800a64e5357fbb2493e4cae061756d145981` there are no significant improvements on build (3.92s for 1.0.0 vs 3.88s for 0.3.1) or test time (21.35s vs 21.59s).
> feat: minimal changes for foundry 1.0.0

- src/improvements/nested.just
export `randomPersonEoa`
**MetaData**
Found this bug in `simulated-run` recipe while locally testing the justfile.
> fix nested justfile bug

- mise.toml
We want to pin our release to foundry v1.0.0, the stable tag will change on the future once they release new versions.
The tag exists here: https://github.com/foundry-rs/foundry/releases/tag/v1.0.0
> Move foundry version from stable to v1.0.0

- src/improvements/justfile
- src/improvements/script/fetch-tasks.sh
- src/improvements/tasks/TaskRunner.sol
[PR](https://github.com/ethereum-optimism/superchain-ops/pull/634) introduced a `sep` directory under `src/improvements/tasks/example/`. This meant that `fetch-tasks.sh` was grabbing not only mainnet but also sepolia tasks to simulated. The forge script command was configured with an ETH_RPC_URL for mainnet. When it came time to simulate the sepolia task, the execution reverted. 
In this PR, I only simulate mainnet tasks. This is a temporary work around and I've made a tracking issue [here](https://github.com/ethereum-optimism/superchain-ops/issues/651) to come back to. We want to make sure the OPCM task that's currently in the `sep` directory gets added to the `eth` directory.
> fix: Fix broken monorepo integration tests.

- tasks/eth/030-soneium-holocene-system-config-upgrade/VALIDATION.md
- Adds a callout to the validation file to ensure signers confirm the domain and message hash
- To check the domain and message hash, you can compare it to the data to sign for the foudnation and security council in a recent simulation of this task: [example](https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-ops/3826/workflows/ad35a06f-4070-4118-aa59-d29b2be7e016/jobs/44443)
> adding expected domain and message hashes callout

- .circleci/config.yml
Our CI has been failing over the last couple of days. This PR silences the alerts we've been receiving until we get a long term fix implemented. We need to have an OPCM task that perfoms an upgrade.
> fix: Silence test failures until we have a long term fix.

- .circleci/config.yml
- src/improvements/justfile
- Ignores failing monorepo-integration-test
- Re-enable CI failure notifications (undo https://github.com/ethereum-optimism/superchain-ops/pull/671)
nit: There are some breaklines and formats applied when i modified and saved config.yml file, not sure if it's because it was not formatted before or i have a different formatter.
> ignore failing tests and reenable Re-enable CI failure notifications

- .circleci/config.yml
I think that the way we setup task specific jobs is unnecessary, and we can instead just convert simulate-nested into a reusable job.
This should make task PRs a bit less noisy and reduce churn in this repo.
> refactor simulate-nested command into a just-simulate-nested job

- src/improvements/AddressRegistry.sol
- src/improvements/tasks/MultisigTask.sol
- src/improvements/tasks/OPCMBaseTask.sol
- src/improvements/tasks/TaskRunner.sol
- src/improvements/template/DisputeGameUpgradeTemplate.sol
- src/improvements/template/EmptyTemplate.template.sol
- src/improvements/template/EnableDeputyPauseModuleTemplate.sol
- src/improvements/template/GasConfigTemplate.sol
- src/improvements/template/SetGameTypeTemplate.sol
- src/improvements/template/TestOPCMUpgradeVxyz.sol
- src/improvements/template/TransferOwnerTemplate.sol
- test/tasks/MultisigTask.t.sol
- test/tasks/SingleMultisigTask.t.sol
- test/tasks/mock/MockDisputeGameTask.sol
- test/tasks/mock/MockMultisigTask.sol
- test/tasks/mock/template/IncorrectGasConfigTemplate1.sol
- test/tasks/mock/template/IncorrectGasConfigTemplate2.sol
Begins decoupling MultisigTask and AddressRegistry. Remaining step is moving `chains` specific things out of `_taskSetup` and into `L2TaskBase`, which will allow us to delete a lot of the duplicate `_deployAddressRegistry` code
cc @prat-gpt @ElliotFriedman
> refactor: start decoupling MultisigTask and AddressRegistry

- .circleci/config.yml
- script/utils/sim-sequence.sh
In this PR,
- Fix Sim-sequence to make better support for sepolia tasks
- Added the task 032 again in the CI, since it worked locally.
- Renaming of the `sim-sequence-1 `->  `sim-sequence-eth`  and same for `sim-sequence-2` -> `sim-sequence-sep` to improve clarity.
> Fix: Sepolia Support for `Sim-Sequence`

- src/improvements/tasks/StateOverrideManager.sol
- test/tasks/StateOverrideManager.t.sol
This PR adds NatSpec to StateOverrideManager and ensures the `_stateOverrides` variable is private to avoid subclasses directly accessing it. The contract is also marked as abstract and various simple refactors have been made for readability improvements.
> StateOverrideManager refactor and NatSpec

- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
This functionality is going to be used later in https://github.com/ethereum-optimism/superchain-ops/pull/664 to make sure that any account accesses on new contracts are **allowed**. 
We are getting all new contracts that are created by looking at the simulations account accesses.
> AccountAccessParser: getNewContracts functionality

- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
This PR implements the sortAccountAccesses function in the AccountAccessParser library using LibSort. The function sorts an array of AccountAccess structs by their account address and returns a new sorted array.
> Implement sortAccountAccesses function using LibSort

- src/improvements/template/EnableDeputyPauseModuleTemplate.sol
- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
Ensuring that sorting happens before state diffs are processed so that decodeAndPrint will print state diffs in address order. Added a test to show this working.
> AccountAccessParser: sorting functionality for state diffs

- ops/verify-geth-endpoint.sh
This PR fix an minor issue that has been introduced two year ago that making the node always returning healthy even if it's not healthy. 
Now instead of returning the full JSON we only return the _block number_. 
**tests** 
I tested this inside `anvil` to make sure this is expected. 
```bash
$ ./ops/verify-geth-endpoint.sh http://localhost:8545
response: {"jsonrpc":"2.0","id":1,"result":false}
Replica is not syncing.
response: {"jsonrpc":"2.0","id":1,"result":"0x0"}
block: 0
Block height is 0.
```
> Fix: Block number Returned is Not Integer. 

- src/improvements/tasks/OPCMBaseTask.sol
- src/improvements/template/EnableDeputyPauseModuleTemplate.sol
- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
This [PR](https://github.com/ethereum-optimism/superchain-ops/pull/743) made sure that we sorted state diffs by address. This allowed us to copy how Tenderly displays state diffs. Upon manual validation of state diffs, I noticed that Tenderly _also_ sorted by slots within an address. This PR implements sorted slot updates by address.
> AccountAccessParser: sorting functionality for slots within an address

- security-council-rehearsals/2024-01-22-r2-remove-signer-0122/justfile
- security-council-rehearsals/templates/r2-remove-signer/justfile
- security-council-rehearsals/templates/r4-jointly-upgrade/justfile
As per discussions in Discord, we're hitting some flaky security council CI tasks. https://discord.com/channels/1244729134312198194/1342572064175030293/1349368472676733050
This allows the tasks to use the foundry.toml rpc url defined for CI.
> fix: Fixing flaky security council ci tasks.

- src/improvements/tasks/TaskRunner.sol
Integration tests are failing because now we have to pass through the child multisig when simulating a nested task.
> fix: Monorepo int tests failing because of TaskRunner.

- src/improvements/nested.just
- src/improvements/single.just
- src/improvements/tasks/MultisigTask.sol
- test/tasks/NestedMultisigTask.t.sol
- test/tasks/example/sep/002-opcm-upgrade-v200/.env
Opting to not use a try catch block when invoking execTransaction on the safe. This means we can simplify the code and also pass through custom gas parameters. 
The new code allows Tenderly gas configuration to be passed through if it's given.
> refactor: execTransaction not using try/catch + allowing specific gas limits to be passed

- justfile
Bumps the eip712sign version to the latest version (`v0.0.11`), which upgrades the go-ethereum version to `v1.15.6`.
**Tests**
No tests added, just a dep bump.
An attempt to solve for #375.
> Bump to eip712sign v0.0.11

- src/improvements/nested.just
- src/improvements/tasks/sep/001-opcm-upgrade-v200/VALIDATION.md
This PR fixes 2 things related to the Base Sepolia 001-opcm-upgrade-v200 task:
1. The `nested.just` file was calling the `get-safe.sh` bash script with the incorrect number of parameters.
2. The expected message hash in the `VALIDATION.md` was not correct and has been replaced with `0xbdd593a729dadfa12c86ebac23914145d1ae0418ef1909ffecf78882d6720212`
> Fix Sepolia 001-opcm-upgrade-v200

- src/improvements/tasks/sep/001-opcm-upgrade-v200/VALIDATION.md
This PR updates the VALIDATION.md file with the correct expected values:
1. The slot for the `approveHash(bytes32)` was incorrect because it was computed form a `txHash` that was itself incorrect  (`0x2c12ddac61031f53730edf4cd4b646a6466872168458222187aed32e4c31d1b3` instead of `0x299045e8050d66c48af7217d72265e91cfea17d4af1d4a70469e26d82119d399`)
2. We redeployed the dispute game implementations recently so the `Raw Old Value`s have been updated with the current ones.
> Fix Sepolia 001-opcm-upgrade-v200 (VALIDATION.md)

- test/tasks/MultisigTask.t.sol
- test/tasks/NestedMultisigTask.t.sol
- test/tasks/StateOverrideManager.t.sol
Sometimes we can see flakes like this one: https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-ops/5523/workflows/936c7d63-14f2-4e7a-a515-899f31e9ce7b/jobs/73695 - If a file doesn't exist to delete then that is okay and we shouldn't revert. 
This PR is super simple:
- It wraps all vm.removeFile calls in a try catch.
> fix: reduce forge test flakiness from vm.removeFile.

- NESTED.md
As discussed [here](https://discord.com/channels/1244729134312198194/1331259603576557599/1355369378006437910). 
This one was a head-scratcher. Turns out Tenderly wasn't decoding the first multicall3 call properly, which led me down the garden path.
> docs: Tenderly bug - mention in NESTED.md

- src/libraries/AccountAccessParser.sol
As per feedback from the first mainnet signing ceremony I've implemented grouping off state diffs by address and added markdown formatting to them. 
For an example of what this looks like checkout this gist: https://gist.github.com/blmalone/3b3d0b03fec70a07d20a64fb4024aaa2 
Example of what it looks like in the terminal:
> refactor: v1 markdown printing for state diffs.

- src/improvements/tasks/eth/001-opcm-upgrade-v200/VALIDATION.md
The current address was incorrectly copied over from the unichain runbook.
> fix base safe address in validations

- src/improvements/tasks/eth/001-opcm-upgrade-v200/README.md
- src/improvements/tasks/eth/001-opcm-upgrade-v200/VALIDATION.md
- src/improvements/tasks/eth/002-opcm-upgrade-v200/README.md
- src/improvements/tasks/eth/002-opcm-upgrade-v200/VALIDATION.md
The use of the generic `child-safe-x` names is causing some confusion, this PR attempts to fix that with documentation.
> Clarify safe addresses in U13 runbooks for base and unichain

- .circleci/config.yml
- tasks/sep/ink-003-set-init-bond/README.md
- tasks/sep/ink-004-enable-permissionless-game/README.md
Ink Sepolia upgraded to use permissionless fault proofs
> executed ink sep move to permissionless

- src/libraries/AccountAccessParser.sol
We want to make sure the markdown for the state diffs in superchain-ops is as easy to read as possible. This PR introduces a few changes to help with that.
See the gist below for an example of what it looks like:
https://gist.github.com/blmalone/3b3d0b03fec70a07d20a64fb4024aaa2
> refactor: markdown update

- mise.toml
- src/improvements/tasks/MultisigTask.sol
- src/improvements/tasks/types/OPCMTaskBase.sol
- src/improvements/template/OPCMUpdatePrestateV300.sol
- src/improvements/template/boilerplate/L2TaskBase.template.sol
- src/improvements/template/boilerplate/OPCMTaskBase.template.sol
- src/improvements/template/boilerplate/SimpleTaskBase.template.sol
- test/tasks/MultisigTask.t.sol
- test/tasks/mock/MockMultisigTask.sol
1. Updated the foundry dependency to: [7a7ad4ea7282c30477d7fc0f39bf631acde7e7bd](https://github.com/foundry-rs/foundry/releases/tag/nightly-7a7ad4ea7282c30477d7fc0f39bf631acde7e7bd). This is to include a fix we've been waiting for to make writing templates work with delegate calls. I opened [this issue](https://github.com/foundry-rs/foundry/issues/9990) on Foundry a number of weeks ago.
2. Included a related fix to the _isValidAction function: https://github.com/ethereum-optimism/superchain-ops/pull/701
3. Added tests to the `_isValidAction` function as they didn't exist before.
> fix: Update Foundry dependency to include fix from Foundry PR #10069

- src/improvements/nested.just
- src/improvements/single.just
- src/improvements/template/OPCMUpgradeV300.sol
- src/improvements/template/boilerplate/OPCMTaskBase.template.sol
- test/tasks/example/sep/006-opcm-upgrade-v300/config.toml
Like OPCMUpdatePrestateV300 template, we're requiring that tasks pass their error strings through their config files.
> feat: opcm v300 add errors as config

- .circleci/config.yml
- src/improvements/tasks/sep/012-opcm-update-prestate-v300-uni/README.md
- src/improvements/tasks/sep/012-opcm-update-prestate-v300-uni/VALIDATION.md
- src/improvements/tasks/sep/012-opcm-update-prestate-v300-uni/config.toml
The unichain devs had added an additional owner to the SAFE wallet, which changed the Message Hash and nonce used in the VALIDATION script
**Tests**
**Metadata**
> fix VALIDATION and config for 012-opcm-update-prestate-v300-uni.

- .circleci/config.yml
- src/improvements/script/check-task-names.sh
We don't want duplicate task names to be added, and we want task names to follow the format `###-`. This simple check enforces that in CI. 
If we need ####- we can do that later in a different PR.
> feat: Checks Applied to Task Directory Names

- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
We were seeing incorrect data in the auto generated state diffs when trying to decode slots that are packed.
> fix: tight variable packing for uint supported in account access parser

- script/utils/sim-sequence.sh
This PR fix a bug with the `stderr` > `stdout` instead making silently fail the single task. 
**tests** 
```bash
./script/utils/sim-sequence.sh eth "006-gas-params-op" # supposed to fail
```
However, the sequence was not failing.
now this is failing as expected.
> FIX: bug with stderr > stdout instead making silently fail single task

- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
Adds a `normalizedStateDiffHash` method to the `AccountAccessParser` library return a normalized state diff hash for a recorded state diff. See the comments above that method for the spec.
There is some currently unimplemented functionality that can be done in a follow up PR, and this puts the scaffolding in place to align on how we normalize state diffs
> feat: mvp of normalized state diff

- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
Fixing one of the TODOs in the AccountAccessParser for the normalization of state diffs.
> fix: more specific approve hash and liveness guard lastLive detection 

- src/improvements/tasks/MultisigTask.sol
- src/improvements/tasks/types/L2TaskBase.sol
- src/libraries/AccountAccessParser.sol
Tried to add similar formatting/colors as op-txverify. This PR is safe to merge as it is only cosmetic and should be fine for existing in progress tasks in the signing ceremony if CI passes. We can let signers know to ignore the tx verify link along with the hash for now. 
These screenshots show how the output in the terminal looks for signers.
> feat: Enable audit hashing and txverify

- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
Fixed bug that was causing `[FAIL: panic: array out-of-bounds access (0x32)]` because an assumption was being made that there could never be more storage writes than accesses.
> fix: Bug in AccountAccessParser resolved

- src/improvements/tasks/eth/006-gas-params-op/README.md
We're going to opt for an approach that slowly increases the gas target instead of doing this increase in one single upgrade.
> fix: mark gas target increase task as cancelled.

- .circleci/config.yml
- src/improvements/README.md
- src/improvements/doc/NEW_TEMPLATE_GUIDE.md
- src/improvements/justfile
- src/improvements/script/create-task.sh
- src/improvements/script/create-template.sh
1. Misc documentation updates.
2. Only running regression tests on main due to the time it takes to run on each PR (see `config.yml` file).
3. `src/improvements/script/create-task.sh` now allows users to create a task in the tests directory. Useful for when you want to test a new template you just created. You can see this by running `just new task`.
4. `src/improvements/script/create-template.sh` - better messaging for when someone is creating a template. You can see this by running `just new template`.
> refactor: CLI improvements and CI update

- .circleci/config.yml
A bunch of old jobs can be removed from CirclCI and I'm adding a slack notification to the template regression tests.
> refactor: circle ci cleanup and slack alert 

- src/improvements/tasks/MultisigTask.sol
- src/improvements/template/OPCMUpgradeV400.sol
- src/libraries/AccountAccessParser.sol
- test/libraries/AccountAccessParser.t.sol
- test/tasks/example/sep/008-opcm-upgrade-stage1/config.toml
The current balance check functionality ignored ERC20 transfers. I've added a helper function in `AccountAccessParser` to be able to determine if the access is a 'value transfer' or not.
> fix: balance change improvements/fixes

- src/improvements/tasks/eth/012-unpause-superchainConfig/README.md
Execute the Unpause of the superchainConfig on Mainnet from today!
> Set `EXECUTED` UnPause SuperchainConfig

- src/improvements/tasks/MultisigTask.sol
- src/improvements/template/OPCMUpgradeV400.sol
We're doing this because we would have to exhaustively list all possible contracts in the template. We had a similar situation with the storage access checks before: https://github.com/ethereum-optimism/superchain-ops/blob/main/src/improvements/tasks/MultisigTask.sol#L639
> fix: Not Adding a balance check to newly deployed contracts

- src/improvements/README.md
We ran into a situation where we wanted to override the PAO address. This clarifies how to do it in the docs.
> docs: Mention precedence when using addresses table in config.toml

- README.md
- src/improvements/SimpleAddressRegistry.sol
- src/improvements/tasks/types/L2TaskBase.sol
- src/improvements/tasks/types/OPCMTaskBase.sol
- src/improvements/tasks/types/SimpleTaskBase.sol
Better comments around order of operations for L2TaskBase superchain address regristy.
> docs: natspec update

- .circleci/config.yml
The new stacked simulations feature wasn't defaulting to use our internal rpc urls. This change fixes this.
> fix: Stacked sim should use ci rpc urls

- src/improvements/tasks/StackedSimulator.sol
Allows the user to set `SIGNING_MODE_IN_PROGRESS=false` in order to force printing of the state diff.
> Enable an override of SIGNING_MODE_IN_PROGRESS to print state diff via StackedSimulator

- src/improvements/tasks/MultisigTask.sol
- src/libraries/MultisigTypes.sol
This PR removes the redundant `Call3Value` struct from `MultisigTypes.sol` and replaces all usages with the imported `IMulticall3.Call3Value` struct from forge-std. This eliminates duplicate code and ensures we're using the standard interface definition.
> refactor(types): Remove redundant type.

- .circleci/config.yml
We're getting timeouts on `main` and it's because we have long running jobs that don't output to the terminal. 
- Error: https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-ops/9822/workflows/82de4dff-e46b-4431-9f12-6fa8ef193b2a/jobs/130053
- Doc describing fix: https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-Hit-Timeout-Limit
> fix: CirclCI no output in terminal timeout increased.

- src/improvements/tasks/sep/016-U16-opcm-upgrade-v400-uni/VALIDATION.md
Enrich Unichain state diff validation with contract names and storage decoding
- Add proper contract names and registry links for newly deployed contracts
- Complete DelayedWETHProxy sections with storage slot decoding and summaries
- Enrich OptimismPortal2 with anchorStateRegistry and ethLockbox slot details
- Add implementation version links to standard-versions-sepolia.toml
- Remove all TODO comments for cleaner validation document
- Mark newly deployed contracts with FLAG for registry update
This PR updates the validation document for the Unichain OPCM upgrade task by:
- Correcting the Safe name from "Nested Safe 1" to "Safe"
- Adding detailed state diff information including:
- ETH transfer from OptimismPortalProxy to EthLockboxProxy
- Storage changes for all affected contracts
- …
> Unichain state diff validation

- src/improvements/template/OPCMUpgradeV200toV400.sol
- test/tasks/example/sep/019-u13-to-u16/config.toml
To avoid creation collision errors, we should use historical prestates instead of using a single prestate for each upgrade.
> fix: use historical prestates for speedrun

- src/improvements/tasks/MultisigTask.sol
Small PR that ensures template devs can assert on state overrides in config.toml files in the `_templateSetup` function.
> fix(overrides): Apply overrides sooner so devs can assert on them in `_templateSetup`

- mise.toml
Moving from `1.22.7` to `1.24.6` based on warning message when trying to run `just install-eip712sign`:
> go: github.com/base/eip712sign@v0.0.11 requires go >= 1.23.0; switching to go1.24.6
> fix: mise go version update

- .circleci/config.yml
We weren't getting slack alerts when forge test failed. We want to be alerted if there are any broken tests on main. Note: this is prone to 502 errors so we will need to keep an eye on this. 
I've also removed rpc urls that aren't being used. RPC urls are included in the `foundry.toml` file instead of the circle ci yaml file.
> fix: CI alerts on forge test

- src/tasks/eth/022-U16a-opcm-upgrade-v410-base/README.md
This PR simply mark's the Base U16a Mainnet Upgrade (`022-U16a-opcm-upgrade-v410-base`) as `READY TO SIGN` in the instructions `README.md`.
> mark 022-U16a-opcm-upgrade-v410-base as READY TO SIGN
